#pragma once

#include "color_ramp_node/color_ramp_node.hh"
#include "construct_planar/construct_planar_node.hh"
#include "construct_spatial/construct_spatial_node.hh"
#include "destruct_planar/destruct_planar_node.hh"
#include "destruct_spatial/destruct_spatial_node.hh"
#include "fractal_noise_texture_node/fractal_noise_texture_node.hh"
#include "intersection_info_node/intersection_info_node.hh"
#include "math_nodes/binary_math_node.hh"
#include "math_nodes/math_operations.hh"
#include "math_nodes/unary_math_node.hh"
#include "mix_node/mix_node.hh"
#include "planar_to_spatial_node/planar_to_spatial_node.hh"
#include "scalar_to_spatial_node/scalar_to_spatial_node.hh"
#include "value_node/value_node.hh"
#include "voronoi_texture_node/voronoi_texture_node.hh"
#include "wave_texture_node/wave_texture_node.hh"
